<?php

/**
 * This is the model base class for the table "userGroup".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserGroup".
 *
 * Columns in table "userGroup" available as properties of the model,
 * followed by relations of table "userGroup" available as properties of the model.
 *
 * @property integer $idUserGroup
 * @property string $name
 * @property string $permissions
 *
 * @property User[] $users
 */
abstract class BaseUserGroup extends GxActiveRecord {


  public static function model( $className = __CLASS__ ) {
    return parent::model( $className );
  }

  public function tableName() {
    return 'usergroup';
  }

  public static function label( $n = 1 ) {
    return Yii::t( 'app', 'Grupo|Grupos', $n );
  }

  public static function representingColumn() {
    return array( 'name' );
  }

  public function rules() {
    return array(
      array( 'name', 'length', 'max' => 100 ),
      array( 'permissions', 'safe' ),
      array( 'permissions', 'required' ),
      array( 'name, permissions', 'default', 'setOnEmpty' => true, 'value' => null ),
      array( 'idUserGroup, name, permissions', 'safe', 'on' => 'search' ),
    );
  }

  public function relations() {
    return array(
      'users' => array( self::HAS_MANY, 'User', 'idUserGroup' ),
    );
  }

  public function pivotModels() {
    return array();
  }

  public function attributeLabels() {
    return array(
      'idUserGroup' => Yii::t( 'app', 'Id User Group' ),
      'name' => Yii::t( 'app', 'Nome' ),
      'permissions' => Yii::t( 'app', 'Permissões' ),
      'users' => null,
    );
  }

  public function search() {
    $criteria = new CDbCriteria;

    $criteria->compare( 'idUserGroup', $this->idUserGroup );
    $criteria->compare( 'name', $this->name, true );
    $criteria->compare( 'permissions', $this->permissions, true );

    return new CActiveDataProvider( $this, array(
      'criteria' => $criteria,
    ) );
  }
}