<?php

/**
 * This is the model base class for the table "assessoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Assessoria".
 *
 * Columns in table "assessoria" available as properties of the model,
 * followed by relations of table "assessoria" available as properties of the model.
 *
 * @property integer $idassessoria
 * @property integer $empreendimento_idempreendimento
 * @property string $titulo
 * @property string $texto
 * @property string $icone
 * @property string $ativo
 *
 * @property Empreendimento $empreendimento
 */
abstract class BaseAssessoria extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'assessoria';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Assessoria', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('empreendimento_idempreendimento', 'required'),
			array('empreendimento_idempreendimento', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>100),
			array('icone', 'length', 'max'=>140),
			array('ativo', 'length', 'max'=>1),
			array('texto', 'safe'),
			array('titulo, texto, icone, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idassessoria, empreendimento_idempreendimento, titulo, texto, icone, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empreendimento' => array(self::BELONGS_TO, 'Empreendimento', 'empreendimento_idempreendimento'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idassessoria' => Yii::t('app', 'Idassessoria'),
			'empreendimento_idempreendimento' => Yii::t('app', 'Empreendimento'),
			'titulo' => Yii::t('app', 'Título'),
			'texto' => Yii::t('app', 'Texto'),
			'icone' => Yii::t('app', 'Icone'),
			'ativo' => Yii::t('app', 'Ativo'),
			'empreendimento' => Yii::t('app', 'Empreendimento'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idassessoria', $this->idassessoria);
		$criteria->compare('empreendimento_idempreendimento', $this->empreendimento_idempreendimento);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('icone', $this->icone, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}