<?php

/**
 * This is the model base class for the table "caracteristica".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Caracteristica".
 *
 * Columns in table "caracteristica" available as properties of the model,
 * followed by relations of table "caracteristica" available as properties of the model.
 *
 * @property integer $idcaracteristica
 * @property integer $ordem
 * @property integer $empreendimento_idempreendimento
 * @property string $titulo
 * @property string $area
 * @property string $imagem
 * @property string $ativo
 *
 * @property Empreendimento $empreendimento
 */
abstract class BaseCaracteristica extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'caracteristica';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Características', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('empreendimento_idempreendimento', 'required'),
			array('ordem, empreendimento_idempreendimento', 'numerical', 'integerOnly'=>true),
			array('titulo, area', 'length', 'max'=>100),
			array('imagem', 'length', 'max'=>140),
			array('ativo', 'length', 'max'=>1),
			array('ordem, titulo, area, imagem, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcaracteristica, ordem, empreendimento_idempreendimento, titulo, area, imagem, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empreendimento' => array(self::BELONGS_TO, 'Empreendimento', 'empreendimento_idempreendimento'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcaracteristica' => Yii::t('app', 'Idcaracteristica'),
			'ordem' => Yii::t('app', 'Ordem'),
			'empreendimento_idempreendimento' => Yii::t('app', 'Empreendimento'),
			'titulo' => Yii::t('app', 'Título'),
			'area' => Yii::t('app', 'Área'),
			'imagem' => Yii::t('app', 'Imagem'),
			'ativo' => Yii::t('app', 'Ativo'),
			'empreendimento' => Yii::t('app', 'Empreendimento'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcaracteristica', $this->idcaracteristica);
		$criteria->compare('ordem', $this->ordem);
		$criteria->compare('empreendimento_idempreendimento', $this->empreendimento_idempreendimento);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('area', $this->area, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}